#!/bin/bash

function getReleaseArray {
    split=$(git describe --abbrev=0 | tr "." " ")
    read -a array <<< $split
}

function pullData {
    git pull origin develop
    git pull origin master
}

function selectLatestHotfix {
    latestVersion=$((${array[2]}+1))
    newVersion=$(($latestVersion+1))
    tag="${array[0]}.${array[1]}.$latestVersion"
    tagNew="${array[0]}.${array[1]}.$newVersion"
    branch="hotfix/$tag"
    branchNew="hotfix/$tagNew"
    checkoutOutput=$(git checkout $branch 2>&1)

    if [[ $checkoutOutput == *"error"* ]]; then
        echo -e "\n\nMissing branch $branch"

    else
        echo -e "$checkoutOutput"
        git pull
    fi
}

function finishHotfix {
    echo "flow hotfix finish $tag -m 'Message'"
    git flow hotfix finish $tag -m "Message"
    echo "push origin develop"
    git push origin develop
    echo "push origin master"
    git push origin master
    echo "push origin $tag"
    git push origin $tag
    echo "flow hotfix start $tagNew"
    git flow hotfix start $tagNew
    echo "push hotfix/$tagNew"
    git push hotfix/$tagNew

}

function deploy {
    pullData
    getReleaseArray
    selectLatestHotfix

    if [[ $checkoutOutput == *"error"* ]]
    then
        return
    else
        if [[ $checkoutOutput == *"fatal"* ]]
        then
            return
        fi
    fi

    finishHotfix

}

deploy


